### PR TITLE
add block number ui

### PR DESCRIPTION
**Pull request by dansofter**

### CODE REVIEW

**Comment by bhgomes** [comment]
@dansofter This is a really great addition! Could we add a link to the block explorer on the circle?

**Comment by dansofter** [comment]
> @dansofter This is a really great addition! Could we add a link to the block explorer on the circle?

@bhgomes What is the link? The polkadot.js app link or dolphin subscan link?

**Comment by bhgomes** [comment]
> > @dansofter This is a really great addition! Could we add a link to the block explorer on the circle?
> 
> 
> 
> @bhgomes What is the link? The polkadot.js app link or dolphin subscan link?

I'd say subscan for now since this matches the link we get from the transaction.

**Review by Kevingislason — APPROVED** [review]
Looks slick

**Pull request merged**
