### PR TITLE
chore: delete docs directory, update PR checklist

### PR DESCRIPTION
**Pull request by omahs**
As mentioned here: https://github.com/Manta-Network/manta-front-end/pull/929#pullrequestreview-1393026029

### CODE REVIEW

**Review by Kevingislason — APPROVED** [review]
Thanks for this!

**Review by jasonintju — COMMENTED** [review]
Perhaps the whole docs folder should be deleted.

**Comment by omahs** [comment]
> Perhaps the whole docs folder should be deleted.

Just updated!

**Comment by jincan39** [comment]
> > Perhaps the whole docs folder should be deleted.
> 
> Just updated!

Thanks for contribution, welcome to Manta open source projects. @omahs

**Pull request merged**
