### PR TITLE
style: navlinks redesign

### PR DESCRIPTION
**Pull request by jincan39**
## Description

closes: #451

---

Before we can merge this PR, please make sure that all the following items have been checked off. If any of the checklist items are not applicable, please leave them but write a little note why.

- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work
- [x] Re-reviewed files changed in the Github PR explorer

## If PR to `staging`
- [x] Updated relevant documentation in the code
- [x] Test code changes manually, and describe your procedure in a comment on this PR
- [x] Mark this PR with the correct milestone

### CODE REVIEW

**Review by Kevingislason — COMMENTED** [review]
When I open the chain selector, I don't see Dolphin. Also, I don't think we want a 'Staking' link on the Dolphin page. Otherwise, code looks good.

**Comment by jincan39** [comment]
> When I open the chain selector, I don't see Dolphin. Also, I don't think we want a 'Staking' link on the Dolphin page. Otherwise, code looks good.

Thanks for notice.  I'll make a confirmation with Chole soon.

**Comment by jasonintju** [comment]
> When I open the chain selector, I don't see Dolphin. Also, I don't think we want a 'Staking' link on the Dolphin page. Otherwise, code looks good.

I think we need to make the interaction clear. Select Network type first, then show different link in the navbar, right? When selecting Calamari, only 'Staking' link be there. When selecting Dolphin, 'Mantapay' 'Bridge' 'Govern' link be there, and 'Mantapay' is the default page for Dolphin Network.
Yeah, confirm this with PM is necessary.

**Review by jasonintju — COMMENTED** [review]
After connecting Manta Signer, the zkAddress button's width is shorter than wallet's button.

**Comment by jincan39** [comment]
> After connecting Manta Signer, the zkAddress button's width is shorter than wallet's button.

nice founding, updated.

**Review by jasonintju — APPROVED** [review]
Looks good

**Review by Kevingislason — APPROVED** [review]

**Review by zhangjing28 — APPROVED** [review]

**Pull request merged**
