### PR TITLE
Staging v5.0.0

### PR DESCRIPTION
**Pull request by Kevingislason**
## Description

Release v5.0.0

additional todos before merging:
- [x] Update v5.0.0 release date in CHANGELOG.mg
- [x] Update minimum required signer version after a new signer has been released

---

Before we can merge this PR, please make sure that all the following items have been checked off. If any of the checklist items are not applicable, please leave them but write a little note why.

- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work
- [x] Re-reviewed files changed in the Github PR explorer

## If PR to `main`
- [x] Update the version number in `package.json` and `src/config/common.json`
- [x] Update the minimum required signer version number in `src/config/common.json` if applicable
- [x] Test following the procedure in `docs/manual_test.md`
- [x] Update `CHANGELOG.md`
- [x] Make sure that all PR's to `manta-signer` and `sdk` on which this PR depends are merged

### CODE REVIEW

**Review by jasonintju — DISMISSED** [review]
great achievement for v5.0.0

**Review by jincan39 — APPROVED** [review]
LGTM

**Review by jasonintju — APPROVED** [review]
happy to release v5.0.0

**Review by jasonintju — APPROVED** [review]
happy to release v5.0.0

**Review by jasonintju — APPROVED** [review]
god bless us

**Review by jincan39 — DISMISSED** [review]
LGTM

**Review by jasonintju — APPROVED** [review]

**Review by jincan39 — APPROVED** [review]
god bless us, smash it.

**Pull request merged**
