### PR TITLE
feat: add talisman configure warning

### PR DESCRIPTION
**Pull request by jasonintju**
## Description

closes: #397 

---

Before we can merge this PR, please make sure that all the following items have been checked off. If any of the checklist items are not applicable, please leave them but write a little note why.

- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work
- [x] Re-reviewed files changed in the Github PR explorer

## If PR to `staging`
- [ ] Updated relevant documentation in the code
- [x] Test code changes manually, and describe your procedure in a comment on this PR
- [ ] Mark this PR with the correct milestone

## If PR to `main`
- [ ] Update the version number in `package.json` and `src/config/common.json`
- [ ] Update the minimum required signer version number in `src/config/common.json` if applicable
- [ ] Test following the procedure in `docs/manual_test.md`
- [ ] Update `CHANGELOG.md`
- [ ] Make sure that all PR's to `manta-signer` and `sdk` on which this PR depends are merged

### CODE REVIEW

**Review by jasonintju — COMMENTED** [review]
Change the attribute of fill of every path to fill="currentColor", then svg will take the color of the font color, so we can change the svg color as we want. It's pretty cool.
I have checked all the components which using this svg, they all worked well.

**Review by Kevingislason — COMMENTED** [review]
How does the app behave when we don't have a polkadot.js account of a SubWallet account? If possible, I think we should generalize this solution so it also handle cases where the user doesn't have a polkadot.js account or a SubWallet account.

**Comment by jasonintju** [comment]
> How does the app behave when we don't have a polkadot.js account of a SubWallet account? If possible, I think we should generalize this solution so it also handle cases where the user doesn't have a polkadot.js account or a SubWallet account.

The other 3 wallets extension(Subwallet, polkadot.js, Metamask) behaved really well. When users click the 'Connect' button, if they don't have a account, the extensions will lead users to create a account first. Really good UX.

Only Talisman wallet needs to be configured first if users have no accounts. Because we didn't handle the Talisman connection error before, when users click the Talisman 'Connect' button, there is no feedback to the users, which is a bad UX. That's why only the Talisman was mentioned in this issue.

**Comment by jincan39** [comment]
image
I experienced the keyring error above when I click the connect Tailsman wallet button.

**Comment by jincan39** [comment]
lgtm

**Review by jincan39 — APPROVED** [review]

**Pull request merged**
